### ISSUE TITLE
Lots of server-code needed.

### ISSUE THREAD

**Issue by trusktr** [kadira-samples/meteor-graphql-demo#4]
So, we have to write lots of GraphQL server code to map to our Mongo collections, which is sort of annoying. It is sort of like writing multiple endpoints, with the exception that only a single endpoint is used...

Is there a better way?

**Comment by arunoda** [comment]
Actually, this is the purest form of writing a schema. You can always write tools to auto generate them. There are a a few projects like this:

This is one for mongoose: https://github.com/RisingStack/graffiti-mongoose
